### ISSUE TITLE
Can't connect to server - also server not showing in steam list

### ISSUE THREAD

**Issue by chlorophant** [japtain-cack/7d2d-server#1]
Followed all the instructions. Looks like I have it up and running on my linux box. I'm not seeing the server listed in the steam server list. No errors in log output. Is there something I'm missing? This is a home server and the box is in the router DMZ (all ports forwarded). When I attempt to "connect to it..." in the game client it just times out.

Any help would be much appreciated.

For reference I cloned this repo and setup a docker-compose that looks like this:

```
version: "3.9"

services:
  sevend2d:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26900:26900/tcp
      - 26900:26902/udp
    volumes:
      - /opt/sevend2d/world1/data:/home/sevend2d/server
      - /opt/sevend2d/world1/saves:/home/sevend2d/.local/share/7DaysToDie/Saves
    environment:
      - SEVEND2D_SERVERNAME=Terminus
 ```

**Comment by chlorophant** [comment]
I see the problem, I had to expose more udp ports

**Comment by japtain-cack** [comment]
Yeah, looks like I need to update the readme. I forgot to add those extra ports.

**Comment by japtain-cack** [comment]
Oh wait, no I think they are listed, but I made a syntax error on one of them.
Here is my entire container deployment config from saltstack, which is working as expected.

```
docker:
  compose:
    ng:
      sevend2d1:
        image: "nsnow/7d2d-server:1"
        container_name: "sevend2d1"
        ports:
          - "26900-26902:26900-26902/udp"
          - "26900:26900/tcp"
        volumes:
          - "/mnt/docker/sevend2d/world1:/home/sevend2d/server"
          - "/mnt/docker/sevend2d/world1_save:/home/sevend2d/.local/share/7DaysToDie"
        environment:
          "SEVEND2D_SERVERNAME": "MIMIR-Tech | 24x7 | XPx2 | BM/5 | AD/1"
          "SEVEND2D_SERVERDESCRIPTION": '"24x7 Server running in my personal docker farm under the stairs. Run it yourself: https://hub.docker.com/r/nsnow/7d2d-server"'
          "SEVEND2D_SERVERWEBSITEURL": "7d2d.mimir-tech.org"
          "SEVEND2D_GAMENAME": "7d2d.mimir-tech.org"
          "SEVEND2D_SERVERMAXWORLDTRANSFERSPEEDKIBS": "1000"
          "SEVEND2D_GAMEDIFFICULTY": "1"
          "SEVEND2D_BLOCKDAMAGEPLAYER": "300"
          "SEVEND2D_BLOCKDAMAGEAI": "50"
          "SEVEND2D_BLOCKDAMAGEAIBM": "50"
          "SEVEND2D_BLOODMOONENEMYCOUNT": "16"
          "SEVEND2D_BLOODMOONFREQUENCY": "5"
          "SEVEND2D_LOOTABUNDANCE": "200"
          "SEVEND2D_LOOTRESPAWNDAYS": "4"
          "SEVEND2D_DROPONDEATH": "0"
          "SEVEND2D_AIRDROPMARKER": '"true"'
          "SEVEND2D_AIRDROPFREQUENCY": "24"
          "SEVEND2D_PARTYSHAREDKILLRANGE": "200"
          "SEVEND2D_PLAYERKILLINGMODE": "2"
          "SEVEND2D_SERVERMAXPLAYERCOUNT": "20"
          "SEVEND2D_LANDCLAIMSIZE": "160"
          "SEVEND2D_LANDCLAIMDECAYMODE": "2"
          "SEVEND2D_XPMULTIPLIER": "200"
          "SEVEND2D_TELNETENABLED": '"false"'
          "SEVEND2D_SERVERADMINSLOTS": "4"
          "SEVEND2D_LANDCLAIMOFFLINEDURABILITYMODIFIER": "0"
        restart: "always"
        tty: True
        stdin_open: True
```
